### PR TITLE
helper for set time

### PR DESCRIPTION
**Pull request by gaionim**
as request in https://github.com/gaionim/rpitx/issues/3

### CODE REVIEW

**Comment by michelinok** [comment]
Hope this will be merged soon with a little tutorial (maybe it would be better if the script could accept date/time as a paremeter)

**Comment by gaionim** [comment]
First I'll try with updated upstream, then I'll add parameters and help.
I think to add offset , positive or negative to now  for manage timezone.
By the way, You said it works;
which length for the antenna wire and  which frequency you  used?

**Comment by gaionim** [comment]
No way, 
updated pi and rpitx, but still  cant set my clock .
Raspberry PI 2 with 6m wire  ( gpio18 and gpio4 ).
I can transmit  105 kHz usb   at 30 cm , so I do non think mi code is working  :-(

**Comment by F5OEO** [comment]
Major update will arrive soon. Solu ve some issues with RFA modes specially
with time accuracy. Wait for updates. Get your git pull but some "confilct
updates". Can I add your script wihout passing by this pull ?

2016-09-01 22:04 GMT+02:00 Mauro <notifications@github.com>:

**Comment by gaionim** [comment]
Yes, You can add the file only,
 but still asking why is working for you.
It is for antenna or is my PI too old?!?

**Comment by gaionim** [comment]
Downloaded updated code from upstream, but nothing.
Now I've reset my clock and at least it see the signal, so not wire problem.
How long took setting your clock ?
After 10 minutes, my is still in the 1998 :-(  before millenium bug )

**Comment by gaionim** [comment]
I may have found a problem:
when I try setTyme I have
...
Error: NTP
.....
when I try  sudo rpitx -m IQ -i ssbIQ.wav -f 105.500 -l -c 1, I have
.....
Calibrate : ppm=88 DMA 157ns:1336ns
......

the complete output is

Use GPCLK Pin instead of PWM
rpitx Version 0.2 compiled Sep  3 2016 (F5OEO Evariste) running on Master PLL = 19200000
memory: 512 MB
processor: Broadcom BCM2835
i2cDevice: /dev/i2c-1
model: Model B
manufacturer: Qisda
pcb revision: 2
warranty void: no
revision: 000f
peripheral base: 0x20000000
Jessie
Using mbox device /dev/vcio.
3616000 Size NUM PAGES 883 PAGE_SIZE 4096
MASH 3 Freq PLL# 1
Error: NTP
WaitNano=14580 F1=77499.997536 TuneFrequency 77500.000000 F2=77500.073910 Initial Resolution(Hz)=0.076373 ResolutionPWMF 0.000830 NbStep=92 DELAYStep=7
****** STARTING TRANSMIT ********

**Comment by gaionim** [comment]
false problem, 
if I launch sudo rpitx -m RFA -i /tmp/pippo.rfa -f 77.5 -l -c 1
( not from inside python ), no error, but still non clock set.
May be is my clock problem ......

**Comment by gaionim** [comment]
git it !!!!
simple fix
-            for val in ( int(v) for v in to_dcf77(start + datetime.timedelta(i))):
+            for val in ( int(v) for v in to_dcf77(start + datetime.timedelta(seconds=i*60))):

but now I can cleanup the code and add parameters.
Close this an I'll reopen soon

**Comment by michelinok** [comment]
Hope to see the fix very soon!
Thanks for your effort!

**Comment by F5OEO** [comment]
for reopen

**Pull request closed without merging**
